# Predicting Medical Insurance using Artificial Neural Network (Regression)
### 18z213 - Bhavadharinie
### 18z218 - Gayathri B
### 18z227 - Kripaa
### 18z237 - Praja SS
### 18z252 - Sneha S

### Importing the libraries

In [1]:
import numpy as np #For working with Arrays
import pandas as pd #For Data Analysis and Manipulation
import tensorflow as tf #For Developing and Training Deep Learning Model

##  Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('insurance.csv') #Imports dataset using read_csv function of pandas library
X = dataset.iloc[:, :-1].values #Extracts all columns excluding last column (Dependent Variable) 
y = dataset.iloc[:, -1].values #Extracts the Dependent Variable

### Encoding Categorical data

In [3]:
from sklearn.compose import ColumnTransformer #Imports ColumnTransformer class from compose module of sklearn library 
from sklearn.preprocessing import OneHotEncoder #Imports OneHotEncoder class from preprocessing module of sklearn library
ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') #Performs One Hot Encoding for the first column alone (sex)
X = np.array(ct1.fit_transform(X)) #Returns a new array with new feature columns
X[0] #Prints the first record in encoded format

array([1.0, 0.0, 19, 27.9, 0, 'yes', 'southwest'], dtype=object)

In [4]:
ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough') #Performs One Hot Encoding for the sixth column alone (region)
X = np.array(ct2.fit_transform(X)) #Returns a new array with new feature columns
X[0] #Prints the first record in encoded format

array([0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 19, 27.9, 0, 'yes'], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder #Imports LabelEncoder class from preprocessing module of sklearn library
le = LabelEncoder() #Creates an object for label encoder class
X[:,9] = le.fit_transform(X[:,9]) #Label encodes the ninth column (smoker) by assigning 1 for smoker and 0 for non-smoker
X[0] #Prints the first record in encoded format

array([0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 19, 27.9, 0, 1], dtype=object)

In [6]:
X = np.asarray(X).astype(np.float32) #Converts the entire array as floating data
X[0] #Prints the first record in final encoded format

array([ 0. ,  0. ,  0. ,  1. ,  1. ,  0. , 19. , 27.9,  0. ,  1. ],
      dtype=float32)

### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split #Imports train_test_split class from model_selection module of sklearn library
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) #Splits the dataset into four sets (20% - test set, 80% - train set)

In [8]:
X_train #Prints X_train

array([[ 0.  ,  0.  ,  0.  , ..., 34.1 ,  4.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , ..., 34.43,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , ..., 36.67,  2.  ,  1.  ],
       ...,
       [ 0.  ,  0.  ,  1.  , ..., 25.08,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ..., 35.53,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ..., 18.5 ,  1.  ,  0.  ]], dtype=float32)

In [9]:
y_train #Prints y_train

array([40182.246 ,  1137.4697, 38511.6283, ...,  5415.6612,  1646.4297,
        4766.022 ])

In [10]:
X_test #Prints x_test

array([[ 0.   ,  0.   ,  0.   , ..., 30.2  ,  1.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   , ..., 29.37 ,  1.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   , ..., 40.565,  2.   ,  1.   ],
       ...,
       [ 1.   ,  0.   ,  0.   , ..., 40.28 ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   , ..., 39.05 ,  3.   ,  1.   ],
       [ 1.   ,  0.   ,  0.   , ..., 24.795,  3.   ,  0.   ]],
      dtype=float32)

In [11]:
y_test #Prints y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

## Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential() #Arranges keras layers in sequential order

### Adding the input layer 

In [13]:
ann.add(tf.keras.layers.Dense(units=120, activation='relu')) #Adds the input layer with 120 hidden neurons and rectified linear activation function

### Adding the first hidden layer 

In [14]:
ann.add(tf.keras.layers.Dense(units=60, activation='relu')) #Adds the first hidden layer with 60 hidden neurons and rectified linear activation function

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=60, activation='relu')) #Adds the second hidden layer with 60 hidden neurons and rectified linear activation function

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1)) #Adds the output layer with one output (Insurance)

## Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error') #Performs stocastic gradient descent with cost function as mean squared error

### Training the ANN model on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 1000) #Fits 32 records in 1 pass recursively with 1000 epochs.Each epoch is one forward and backward pass for all the training records. 

Epoch 1/1000
34/34 [==============================] - 1s 2ms/step - loss: 322989587.2000
Epoch 2/1000
34/34 [==============================] - 0s 2ms/step - loss: 296792720.4571
Epoch 3/1000
34/34 [==============================] - 0s 2ms/step - loss: 280786941.2571
Epoch 4/1000
34/34 [==============================] - 0s 2ms/step - loss: 198070618.0571
Epoch 5/1000
34/34 [==============================] - 0s 2ms/step - loss: 128866935.3143
Epoch 6/1000
34/34 [==============================] - 0s 2ms/step - loss: 135116912.4571
Epoch 7/1000
34/34 [==============================] - 0s 2ms/step - loss: 127279265.3714
Epoch 8/1000
34/34 [==============================] - 0s 2ms/step - loss: 122707997.4857
Epoch 9/1000
34/34 [==============================] - 0s 2ms/step - loss: 119564624.0000
Epoch 10/1000
34/34 [==============================] - 0s 2ms/step - loss: 116319094.8571
Epoch 11/1000
34/34 [==============================] - 0s 2ms/step - loss: 124034882.5143
Epoch 12/1000
34/34

34/34 [==============================] - 0s 2ms/step - loss: 35381036.5143
Epoch 93/1000
34/34 [==============================] - 0s 2ms/step - loss: 36981240.5143
Epoch 94/1000
34/34 [==============================] - 0s 2ms/step - loss: 35903584.8000
Epoch 95/1000
34/34 [==============================] - 0s 2ms/step - loss: 35171685.5429
Epoch 96/1000
34/34 [==============================] - 0s 2ms/step - loss: 35020882.7429
Epoch 97/1000
34/34 [==============================] - 0s 2ms/step - loss: 31119559.6000
Epoch 98/1000
34/34 [==============================] - 0s 2ms/step - loss: 34080246.5714
Epoch 99/1000
34/34 [==============================] - 0s 2ms/step - loss: 32444261.2571
Epoch 100/1000
34/34 [==============================] - 0s 2ms/step - loss: 33969098.8571
Epoch 101/1000
34/34 [==============================] - 0s 1ms/step - loss: 38893107.3143
Epoch 102/1000
34/34 [==============================] - 0s 1ms/step - loss: 32575045.9429
Epoch 103/1000
34/34 [==========

34/34 [==============================] - 0s 2ms/step - loss: 29661460.6286
Epoch 183/1000
34/34 [==============================] - 0s 2ms/step - loss: 28666469.8286
Epoch 184/1000
34/34 [==============================] - 0s 2ms/step - loss: 31926811.6571
Epoch 185/1000
34/34 [==============================] - 0s 1ms/step - loss: 27835364.9143
Epoch 186/1000
34/34 [==============================] - 0s 1ms/step - loss: 30572006.8571
Epoch 187/1000
34/34 [==============================] - 0s 1ms/step - loss: 29228479.4857
Epoch 188/1000
34/34 [==============================] - 0s 1ms/step - loss: 28288467.5429
Epoch 189/1000
34/34 [==============================] - 0s 1ms/step - loss: 30305887.4286
Epoch 190/1000
34/34 [==============================] - 0s 1ms/step - loss: 24602069.4286
Epoch 191/1000
34/34 [==============================] - 0s 2ms/step - loss: 27748129.4857
Epoch 192/1000
34/34 [==============================] - 0s 2ms/step - loss: 25545472.8571
Epoch 193/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 24005037.5429
Epoch 273/1000
34/34 [==============================] - 0s 2ms/step - loss: 26837679.6000
Epoch 274/1000
34/34 [==============================] - 0s 2ms/step - loss: 22002416.2714
Epoch 275/1000
34/34 [==============================] - 0s 2ms/step - loss: 22846603.3143
Epoch 276/1000
34/34 [==============================] - 0s 1ms/step - loss: 26299015.1429
Epoch 277/1000
34/34 [==============================] - 0s 1ms/step - loss: 26533095.0857
Epoch 278/1000
34/34 [==============================] - 0s 1ms/step - loss: 23815685.3143
Epoch 279/1000
34/34 [==============================] - 0s 1ms/step - loss: 24941320.8571
Epoch 280/1000
34/34 [==============================] - 0s 1ms/step - loss: 24367509.0857
Epoch 281/1000
34/34 [==============================] - 0s 1ms/step - loss: 23711632.6000
Epoch 282/1000
34/34 [==============================] - 0s 1ms/step - loss: 24367229.3714
Epoch 283/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 25965594.0000
Epoch 364/1000
34/34 [==============================] - 0s 2ms/step - loss: 25768853.4857
Epoch 365/1000
34/34 [==============================] - 0s 2ms/step - loss: 28077908.6286
Epoch 366/1000
34/34 [==============================] - 0s 2ms/step - loss: 23653384.7429
Epoch 367/1000
34/34 [==============================] - 0s 2ms/step - loss: 23659472.8000
Epoch 368/1000
34/34 [==============================] - 0s 2ms/step - loss: 22081610.5714
Epoch 369/1000
34/34 [==============================] - 0s 1ms/step - loss: 22047624.0286
Epoch 370/1000
34/34 [==============================] - 0s 1ms/step - loss: 20603082.8857
Epoch 371/1000
34/34 [==============================] - 0s 1ms/step - loss: 24269697.2000
Epoch 372/1000
34/34 [==============================] - 0s 1ms/step - loss: 23876804.7429
Epoch 373/1000
34/34 [==============================] - 0s 1ms/step - loss: 23253125.1429
Epoch 374/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 24684483.3714
Epoch 455/1000
34/34 [==============================] - 0s 2ms/step - loss: 21757099.4571
Epoch 456/1000
34/34 [==============================] - 0s 1ms/step - loss: 25356764.1714
Epoch 457/1000
34/34 [==============================] - 0s 1ms/step - loss: 24242902.0571
Epoch 458/1000
34/34 [==============================] - 0s 1ms/step - loss: 20765575.6429
Epoch 459/1000
34/34 [==============================] - 0s 1ms/step - loss: 23796656.1143
Epoch 460/1000
34/34 [==============================] - 0s 1ms/step - loss: 21702703.8857
Epoch 461/1000
34/34 [==============================] - 0s 1ms/step - loss: 21807696.0286
Epoch 462/1000
34/34 [==============================] - 0s 2ms/step - loss: 21296190.8000
Epoch 463/1000
34/34 [==============================] - 0s 2ms/step - loss: 21830598.2857
Epoch 464/1000
34/34 [==============================] - 0s 2ms/step - loss: 23325738.6857
Epoch 465/1000
34/34 [===

34/34 [==============================] - 0s 1ms/step - loss: 22177846.6857
Epoch 546/1000
34/34 [==============================] - 0s 1ms/step - loss: 23516292.6857
Epoch 547/1000
34/34 [==============================] - 0s 1ms/step - loss: 23733637.0286
Epoch 548/1000
34/34 [==============================] - 0s 1ms/step - loss: 22379858.6286
Epoch 549/1000
34/34 [==============================] - 0s 1ms/step - loss: 22999517.8857
Epoch 550/1000
34/34 [==============================] - 0s 1ms/step - loss: 24335162.8286
Epoch 551/1000
34/34 [==============================] - 0s 2ms/step - loss: 24254222.9714
Epoch 552/1000
34/34 [==============================] - 0s 1ms/step - loss: 22802949.7714
Epoch 553/1000
34/34 [==============================] - 0s 2ms/step - loss: 22184086.8000
Epoch 554/1000
34/34 [==============================] - 0s 2ms/step - loss: 21062760.4286
Epoch 555/1000
34/34 [==============================] - 0s 2ms/step - loss: 24896513.2000
Epoch 556/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 21138914.7429
Epoch 637/1000
34/34 [==============================] - 0s 2ms/step - loss: 19886616.8857
Epoch 638/1000
34/34 [==============================] - 0s 2ms/step - loss: 23599335.8000
Epoch 639/1000
34/34 [==============================] - 0s 2ms/step - loss: 21127777.8857
Epoch 640/1000
34/34 [==============================] - 0s 2ms/step - loss: 20911431.8286
Epoch 641/1000
34/34 [==============================] - 0s 2ms/step - loss: 26700271.9429
Epoch 642/1000
34/34 [==============================] - 0s 2ms/step - loss: 24615168.9714
Epoch 643/1000
34/34 [==============================] - 0s 2ms/step - loss: 27648186.8571
Epoch 644/1000
34/34 [==============================] - 0s 2ms/step - loss: 23210161.8857
Epoch 645/1000
34/34 [==============================] - 0s 1ms/step - loss: 24667051.2000
Epoch 646/1000
34/34 [==============================] - 0s 1ms/step - loss: 21293152.9143
Epoch 647/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 23764990.9143
Epoch 727/1000
34/34 [==============================] - 0s 2ms/step - loss: 21133714.0286
Epoch 728/1000
34/34 [==============================] - 0s 2ms/step - loss: 20569944.4286
Epoch 729/1000
34/34 [==============================] - 0s 2ms/step - loss: 24566650.0571
Epoch 730/1000
34/34 [==============================] - 0s 2ms/step - loss: 24065476.7429
Epoch 731/1000
34/34 [==============================] - 0s 1ms/step - loss: 22935914.6286
Epoch 732/1000
34/34 [==============================] - ETA: 0s - loss: 23768439.48 - 0s 2ms/step - loss: 23563161.8857
Epoch 733/1000
34/34 [==============================] - 0s 2ms/step - loss: 21385050.2000
Epoch 734/1000
34/34 [==============================] - 0s 1ms/step - loss: 24083086.2286
Epoch 735/1000
34/34 [==============================] - 0s 1ms/step - loss: 24345406.2857
Epoch 736/1000
34/34 [==============================] - 0s 1ms/step - loss: 21824712.

34/34 [==============================] - 0s 1ms/step - loss: 20093516.9429
Epoch 817/1000
34/34 [==============================] - 0s 2ms/step - loss: 24037961.6000
Epoch 818/1000
34/34 [==============================] - 0s 2ms/step - loss: 21328701.8286
Epoch 819/1000
34/34 [==============================] - 0s 1ms/step - loss: 20749451.7429
Epoch 820/1000
34/34 [==============================] - 0s 2ms/step - loss: 21456396.9143
Epoch 821/1000
34/34 [==============================] - 0s 2ms/step - loss: 20042997.2000
Epoch 822/1000
34/34 [==============================] - 0s 2ms/step - loss: 27740921.0286
Epoch 823/1000
34/34 [==============================] - 0s 2ms/step - loss: 24294257.8857
Epoch 824/1000
34/34 [==============================] - 0s 2ms/step - loss: 20783772.1429
Epoch 825/1000
34/34 [==============================] - 0s 2ms/step - loss: 17497860.2857
Epoch 826/1000
34/34 [==============================] - 0s 2ms/step - loss: 22703664.0571
Epoch 827/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 20831185.9429
Epoch 908/1000
34/34 [==============================] - 0s 2ms/step - loss: 21541224.8000
Epoch 909/1000
34/34 [==============================] - 0s 2ms/step - loss: 20431040.2286
Epoch 910/1000
34/34 [==============================] - 0s 2ms/step - loss: 18890227.6000
Epoch 911/1000
34/34 [==============================] - 0s 2ms/step - loss: 18806140.5714
Epoch 912/1000
34/34 [==============================] - 0s 2ms/step - loss: 24350823.7143
Epoch 913/1000
34/34 [==============================] - 0s 2ms/step - loss: 19495783.6571
Epoch 914/1000
34/34 [==============================] - 0s 2ms/step - loss: 22133478.7714
Epoch 915/1000
34/34 [==============================] - 0s 2ms/step - loss: 25243110.5143
Epoch 916/1000
34/34 [==============================] - 0s 2ms/step - loss: 24460225.1429
Epoch 917/1000
34/34 [==============================] - 0s 1ms/step - loss: 22435416.0571
Epoch 918/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 21485162.6857
Epoch 998/1000
34/34 [==============================] - 0s 2ms/step - loss: 24729293.9429
Epoch 999/1000
34/34 [==============================] - 0s 2ms/step - loss: 21342267.1571
Epoch 1000/1000
34/34 [==============================] - 0s 2ms/step - loss: 21190134.6000


### Predicting the results of the Test set

In [20]:
import sklearn.metrics as sm #Imports metrics from sklearn library
y_pred = ann.predict(X_test) #Predicts the output for each record in the test set

In [21]:
np.set_printoptions(precision=2) #Sets precision of print statement to 2
print(round(sm.r2_score(y_test, y_pred), 2)) #Prints the R2 Score i.e.,a Statistical measure of how close the data is to the fitted regression line. 

0.88


In [22]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #Concatenates the predicted and actual values of X_test to compare the results

[[11172.03  9724.53]
 [ 9627.04  8547.69]
 [49852.44 45702.02]
 [13568.83 12950.07]
 [ 9502.61  9644.25]
 [ 4848.53  4500.34]
 [ 3626.51  2198.19]
 [14747.4  11436.74]
 [10016.04  7537.16]
 [ 8353.65  5425.02]
 [ 6620.61  6753.04]
 [11681.71 10493.95]
 [ 7633.37  7337.75]
 [ 5151.79  4185.1 ]
 [23428.07 18310.74]
 [13729.54 10702.64]
 [13535.92 12523.6 ]
 [ 6048.11  3490.55]
 [ 8102.99  6457.84]
 [26027.25 33475.82]
 [25165.07 23967.38]
 [14925.35 12643.38]
 [11271.4  23045.57]
 [27506.92 23065.42]
 [ 3470.26  1674.63]
 [ 7190.61  4667.61]
 [ 4350.48  3732.63]
 [ 8485.23  7682.67]
 [ 4657.14  3756.62]
 [10165.17  8413.46]
 [ 9836.56  8059.68]
 [52263.96 48970.25]
 [13720.02 12979.36]
 [10507.09 20630.28]
 [15087.02 14571.89]
 [ 5676.75  4137.52]
 [ 9149.36  8347.16]
 [36296.96 51194.56]
 [37446.41 40003.33]
 [ 2125.    1880.49]
 [ 6221.06  5458.05]
 [ 4561.74  2867.12]
 [24503.21 20149.32]
 [49851.95 47496.49]
 [33133.32 36149.48]
 [ 6291.65 26018.95]
 [13645.51 19749.38]
 [ 7460.66  6

### Predicting insurance value for user input

In [23]:
l=[] #Creates an empty input list
dict_sex={'Male':[0.0,1.0],'Female':[1.0,0.0]} #Maps gender to its encoded value using dictionary
dict_region={'Southwest':[1.0,0.0,0.0,0.0],'Southeast':[0.0,1.0,0.0,0.0],'Northwest':[0.0,0.0,1.0,0.0],'Northeast':[0.0,0.0,0.0,1.0]} #Maps region to its encoded value using dictionary
region=input("Region: ") #Takes Region as input (Accepted values - Southwest, Southeast, Northwest, Northeast)
l.extend(dict_region[region]) #Appends the encoded value of region to the input list
sex=input("Sex: ") #Takes Sex as input (Accepted values - Female, Male)
l.extend(dict_sex[sex]) #Appends the encoded value of sex to the input list
age=float(input("Age: ")) #Takes Age as input (Accepted values - Valid age)
l.append(age) #Appends age to the input list
bmi=float(input("BMI: ")) #Takes BMI as input (Accepted values - Valid BMI value)
l.append(bmi) #Appends bmi to the input list
child=float(input("Children: ")) #Takes Children as input (Accepted values - Whole numbers)
l.append(child) #Appends number of children to the input list
smoker=input("Smoker: ") #Takes Smoker as input (Accepted values - Yes, No)
if smoker=="Yes": #Checks if smoker value is Yes
    l.append(1.0) #Appends 1.0 if Yes
else: #If smoker is not Yes i.e. value is No
    l.append(0.0) #Appends 0.0 if No
print(ann.predict([l])) #Predict insurance value for input list

Region: Southeast
Sex: Female
Age: 30
BMI: 24.24
Children: 0
Smoker: No
[[3998.99]]
