# Artificial Neural Network - Regression 

### Importing the libraries

In [319]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [320]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [321]:
dataset = pd.read_csv('insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [322]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct1.fit_transform(X))
X[0]

array([1.0, 0.0, 19, 27.9, 0, 'yes', 'southwest'], dtype=object)

In [323]:
ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
X = np.array(ct2.fit_transform(X))
X[0]

array([0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 19, 27.9, 0, 'yes'], dtype=object)

In [324]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(X[:,9])
X[:,9] = le.fit_transform(X[:,9])

In [325]:
X = np.asarray(X).astype(np.float32)
X[0]

array([ 0. ,  0. ,  0. ,  1. ,  1. ,  0. , 19. , 27.9,  0. ,  1. ],
      dtype=float32)

### Splitting the dataset into the Training set and Test set

In [326]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train

array([[ 0.  ,  0.  ,  0.  , ..., 34.1 ,  4.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , ..., 34.43,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , ..., 36.67,  2.  ,  1.  ],
       ...,
       [ 0.  ,  0.  ,  1.  , ..., 25.08,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ..., 35.53,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ..., 18.5 ,  1.  ,  0.  ]], dtype=float32)

In [327]:
(X[0,-1])

1.0

## Part 2 - Building the ANN

### Initializing the ANN

In [328]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [329]:
ann.add(tf.keras.layers.Dense(units=120, activation='relu'))

In [330]:
ann.add(tf.keras.layers.Dense(units=60, activation='relu'))
ann.add(tf.keras.layers.Dense(units=60, activation='relu'))

### Adding the second hidden layer

In [331]:
ann.add(tf.keras.layers.Dense(units=60, activation='relu'))

### Adding the output layer

In [332]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [333]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [334]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 1000)

Epoch 1/1000
34/34 [==============================] - 1s 2ms/step - loss: 329198050.7429
Epoch 2/1000
34/34 [==============================] - 0s 2ms/step - loss: 306951548.8000
Epoch 3/1000
34/34 [==============================] - 0s 2ms/step - loss: 223957639.7714
Epoch 4/1000
34/34 [==============================] - 0s 1ms/step - loss: 126618888.9143
Epoch 5/1000
34/34 [==============================] - 0s 2ms/step - loss: 132374321.3714
Epoch 6/1000
34/34 [==============================] - 0s 2ms/step - loss: 128464568.9143
Epoch 7/1000
34/34 [==============================] - 0s 2ms/step - loss: 123517769.1429
Epoch 8/1000
34/34 [==============================] - 0s 2ms/step - loss: 124039558.8571
Epoch 9/1000
34/34 [==============================] - 0s 2ms/step - loss: 132393493.7143
Epoch 10/1000
34/34 [==============================] - 0s 1ms/step - loss: 128502483.2000
Epoch 11/1000
34/34 [==============================] - 0s 2ms/step - loss: 126514360.4571
Epoch 12/1000
34/34

34/34 [==============================] - 0s 2ms/step - loss: 21365418.1714
Epoch 184/1000
34/34 [==============================] - 0s 1ms/step - loss: 24483010.8000
Epoch 185/1000
34/34 [==============================] - 0s 1ms/step - loss: 26012471.8857
Epoch 186/1000
34/34 [==============================] - 0s 1ms/step - loss: 23175129.0000
Epoch 187/1000
34/34 [==============================] - 0s 2ms/step - loss: 26510164.3429
Epoch 188/1000
34/34 [==============================] - 0s 2ms/step - loss: 20585593.3143
Epoch 189/1000
34/34 [==============================] - 0s 2ms/step - loss: 24714217.4286
Epoch 190/1000
34/34 [==============================] - 0s 2ms/step - loss: 23314536.9714
Epoch 191/1000
34/34 [==============================] - 0s 1ms/step - loss: 25345953.7143
Epoch 192/1000
34/34 [==============================] - 0s 1ms/step - loss: 22174949.4000
Epoch 193/1000
34/34 [==============================] - 0s 2ms/step - loss: 25349256.5714
Epoch 194/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 24744929.0286
Epoch 365/1000
34/34 [==============================] - 0s 2ms/step - loss: 26461808.0000
Epoch 366/1000
34/34 [==============================] - 0s 1ms/step - loss: 24975111.2000
Epoch 367/1000
34/34 [==============================] - 0s 1ms/step - loss: 24434472.5714
Epoch 368/1000
34/34 [==============================] - 0s 2ms/step - loss: 21960316.8571
Epoch 369/1000
34/34 [==============================] - 0s 1ms/step - loss: 22958406.8571
Epoch 370/1000
34/34 [==============================] - 0s 1ms/step - loss: 24151516.6286
Epoch 371/1000
34/34 [==============================] - 0s 1ms/step - loss: 22826820.0571
Epoch 372/1000
34/34 [==============================] - 0s 1ms/step - loss: 22281512.9000
Epoch 373/1000
34/34 [==============================] - 0s 1ms/step - loss: 20918100.8000
Epoch 374/1000
34/34 [==============================] - 0s 2ms/step - loss: 19559103.3429
Epoch 375/1000
34/34 [===

34/34 [==============================] - 0s 2ms/step - loss: 21555909.7429
Epoch 546/1000
34/34 [==============================] - 0s 2ms/step - loss: 22411263.5000
Epoch 547/1000
34/34 [==============================] - 0s 1ms/step - loss: 18896076.5143
Epoch 548/1000
34/34 [==============================] - 0s 1ms/step - loss: 23302596.6857
Epoch 549/1000
34/34 [==============================] - 0s 1ms/step - loss: 21157432.9714
Epoch 550/1000
34/34 [==============================] - 0s 2ms/step - loss: 17429835.4571
Epoch 551/1000
34/34 [==============================] - 0s 1ms/step - loss: 24170526.9143
Epoch 552/1000
34/34 [==============================] - 0s 2ms/step - loss: 22184780.0000
Epoch 553/1000
34/34 [==============================] - 0s 2ms/step - loss: 20306779.1714
Epoch 554/1000
34/34 [==============================] - 0s 2ms/step - loss: 23205628.5143
Epoch 555/1000
34/34 [==============================] - 0s 2ms/step - loss: 25393304.4000
Epoch 556/1000
34/34 [===

34/34 [==============================] - 0s 1ms/step - loss: 19258022.2571
Epoch 728/1000
34/34 [==============================] - 0s 2ms/step - loss: 19655996.6000
Epoch 729/1000
34/34 [==============================] - 0s 1ms/step - loss: 17845656.7143
Epoch 730/1000
34/34 [==============================] - 0s 2ms/step - loss: 16176749.6857
Epoch 731/1000
34/34 [==============================] - 0s 1ms/step - loss: 21276504.0286
Epoch 732/1000
34/34 [==============================] - 0s 1ms/step - loss: 24278628.8000
Epoch 733/1000
34/34 [==============================] - 0s 1ms/step - loss: 20151226.1143
Epoch 734/1000
34/34 [==============================] - 0s 1ms/step - loss: 17671030.1714
Epoch 735/1000
34/34 [==============================] - 0s 2ms/step - loss: 23085415.2286
Epoch 736/1000
34/34 [==============================] - 0s 2ms/step - loss: 21833798.4000
Epoch 737/1000
34/34 [==============================] - 0s 1ms/step - loss: 22108387.8857
Epoch 738/1000
34/34 [===

Epoch 818/1000
34/34 [==============================] - 0s 2ms/step - loss: 22015609.7429
Epoch 819/1000
34/34 [==============================] - 0s 2ms/step - loss: 18147750.2571
Epoch 820/1000
34/34 [==============================] - 0s 2ms/step - loss: 20442313.7714
Epoch 821/1000
34/34 [==============================] - 0s 1ms/step - loss: 17967944.4571
Epoch 822/1000
34/34 [==============================] - 0s 1ms/step - loss: 21767719.5429
Epoch 823/1000
34/34 [==============================] - 0s 1ms/step - loss: 19665085.9143
Epoch 824/1000
34/34 [==============================] - 0s 1ms/step - loss: 19234660.8571
Epoch 825/1000
34/34 [==============================] - 0s 2ms/step - loss: 18359813.2000
Epoch 826/1000
34/34 [==============================] - 0s 2ms/step - loss: 19563066.5714
Epoch 827/1000
34/34 [==============================] - 0s 2ms/step - loss: 16546143.9714
Epoch 828/1000
34/34 [==============================] - 0s 2ms/step - loss: 22488095.4286
Epoch 829/

34/34 [==============================] - 0s 2ms/step - loss: 21182725.3143
Epoch 910/1000
34/34 [==============================] - 0s 2ms/step - loss: 21340992.1143
Epoch 911/1000
34/34 [==============================] - 0s 2ms/step - loss: 19757814.6000
Epoch 912/1000
34/34 [==============================] - 0s 1ms/step - loss: 21927049.4286
Epoch 913/1000
34/34 [==============================] - 0s 1ms/step - loss: 18532265.8571
Epoch 914/1000
34/34 [==============================] - 0s 2ms/step - loss: 19826567.4857
Epoch 915/1000
34/34 [==============================] - 0s 2ms/step - loss: 20119211.1429
Epoch 916/1000
34/34 [==============================] - 0s 2ms/step - loss: 19589778.2857
Epoch 917/1000
34/34 [==============================] - 0s 2ms/step - loss: 17205244.0000
Epoch 918/1000
34/34 [==============================] - 0s 1ms/step - loss: 17995215.1714
Epoch 919/1000
34/34 [==============================] - 0s 1ms/step - loss: 17111309.3714
Epoch 920/1000
34/34 [===

### Predicting the results of the Test set

In [335]:
import sklearn.metrics as sm
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(round(sm.r2_score(y_test, y_pred), 2))
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

0.88
[[10361.59  9724.53]
 [ 9044.01  8547.69]
 [47753.52 45702.02]
 [11457.78 12950.07]
 [ 9047.89  9644.25]
 [ 3056.62  4500.34]
 [ 2770.39  2198.19]
 [13152.04 11436.74]
 [ 8460.7   7537.16]
 [ 8501.62  5425.02]
 [ 6600.27  6753.04]
 [10334.96 10493.95]
 [ 7569.    7337.75]
 [ 4504.9   4185.1 ]
 [17803.09 18310.74]
 [13782.36 10702.64]
 [12772.87 12523.6 ]
 [ 5122.62  3490.55]
 [ 6983.02  6457.84]
 [28933.11 33475.82]
 [23260.66 23967.38]
 [13836.91 12643.38]
 [10564.35 23045.57]
 [23118.04 23065.42]
 [ 4150.28  1674.63]
 [ 6088.28  4667.61]
 [ 5188.77  3732.63]
 [ 7347.9   7682.67]
 [ 4055.66  3756.62]
 [ 8528.28  8413.46]
 [ 8528.28  8059.68]
 [48841.48 48970.25]
 [12182.47 12979.36]
 [ 9802.27 20630.28]
 [14189.44 14571.89]
 [ 4475.99  4137.52]
 [ 8336.83  8347.16]
 [37217.53 51194.56]
 [43007.72 40003.33]
 [ 1404.54  1880.49]
 [ 6266.49  5458.05]
 [ 4424.18  2867.12]
 [24522.33 20149.32]
 [50260.64 47496.49]
 [37069.15 36149.48]
 [ 6273.95 26018.95]
 [13631.16 19749.38]
 [ 7598.

In [344]:
l=[]
dict_sex={'Male':[0.0,1.0],'Female':[1.0,0.0]}
dict_region={'Southwest':[1.0,0.0,0.0,0.0],'Southeast':[0.0,1.0,0.0,0.0],'Northwest':[0.0,0.0,1.0,0.0],'Northeast':[0.0,0.0,0.0,1.0]}
region=input("Region: ")
l.extend(dict_region[region])
sex=input("Sex: ")
l.extend(dict_sex[sex])
age=float(input("Age: "))
l.append(age)
bmi=float(input("BMI: "))
l.append(bmi)
child=float(input("Children: "))
l.append(child)
smoker=input("Smoker: ")
if smoker=="yes":
    l.append(1.0)
else:
    l.append(0.0)
print(ann.predict([l]))

Region: Northeast
Sex: Female
Age: 52
BMI: 30.78
Children: 1
Smoker: no
[[10703.42]]
